trigger:
- master   # or main

pool:
  vmImage: 'windows-latest'

steps:
- task: IISWebAppManagementOnMachineGroup@0
  inputs:
    IISDeploymentType: 'IISWebsite'
    ActionIISWebsite: 'CreateOrUpdateWebsite'
    WebsiteName: 'Thematrixapi'
    WebsitePhysicalPath: 'C:\inetpub\wwwroot\Thematrixapi'
    WebsitePhysicalPathAuth: 'WebsiteWindowsAuth'
    WebsiteAuthUserName: 'admin'
    WebsiteAuthUserPassword: '$(WebsiteAuthPassword)'  # use secret variable
    ConfigureAuthenticationForWebsite: true
