name: "Build and Deploy"
on:
  push:
    branches:
      - master

env:
  WEBAPP_NAME: 'IISAutoDeploy'
  DOTNET_VERSION: '8.0.x'           # set this to the dot net version to use
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core 
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Install dependencies
        working-directory: 'IISAutoDeploy'
        run: dotnet restore
        
      - name: Build
        working-directory: 'IISAutoDeploy'
        run: dotnet build --configuration Release --no-restore
        
      - name: Publish
        working-directory: 'IISAutoDeploy'
        run: dotnet publish --configuration Release --output 'dotnetcorewebapp'

    # 7️⃣ Deploy to IIS
      - name: Deploy to IIS
        uses: RasmusBuchholdt/simply-web-deploy@2.0.0
        with:
          website-name: 'Thematrixapi'
          server-computer-name: 'https://107.161.168.33:8172/msdeploy.axd'
          server-username: 'admin'
          server-password: 'Abdomatrixsak@123'
          source-path: '/IISAutoDeploy/dotnetcorewebapp/'
          target-delete: true
